# ${1}: path to the Taiwan-LLaMa checkpoint folder

python src/train_bash.py \
    --stage sft \
    --model_name_or_path ${1} \
    --do_train True \
    --finetuning_type lora \
    --quantization_bit 4 \
    --template default \
    --flash_attn True \
    --shift_attn False \
    --dataset_dir data \
    --dataset train \
    --cutoff_len 1024 \
    --learning_rate 1e-05 \
    --num_train_epochs 10 \
    --max_samples 10000 \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 16 \
    --lr_scheduler_type cosine \
    --max_grad_norm 1.0 \
    --logging_steps 5 \
    --save_steps 100 \
    --warmup_steps 0 \
    --neft_alpha 0 \
    --train_on_prompt False \
    --upcast_layernorm True \
    --lora_rank 8 \
    --lora_dropout 0.1 \
    --lora_target q_proj,v_proj \
    --resume_lora_training True \
    --output_dir saved_model \
    --bf16 True
